live_config_reload = true

[bell]
animation = "EaseOutQuint"
color = "#2e3440"
duration = 6

[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x0b0c0e"
foreground = "0xc5cad3"

[font]
size = 24.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = 1
y = 0

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[schemes.material.bright]
black = "#4e4e4e"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#f07178"
red = "#ff5370"
white = "#ffffff"
yellow = "#ffcb6b"

[schemes.material.normal]
black = "#000000"
blue = "#6182b8"
cyan = "#39adb5"
green = "#91b859"
magenta = "#ff5370"
red = "#e53935"
white = "#a0a0a0"
yellow = "#ffb62c"

[schemes.material.primary]
background = "#263238"
foreground = "#eeffff"

[schemes.material_iterm.bright]
black = "#002833"
blue = "#0084cb"
cyan = "#006ba5"
green = "#1b9d00"
magenta = "#b333e1"
red = "#e9244f"
white = "#e7e7e7"
yellow = "#d7a301"

[schemes.material_iterm.normal]
black = "#003440"
blue = "#3fade5"
cyan = "#5c87b1"
green = "#6dc04c"
magenta = "#e07bff"
red = "#ed5165"
white = "#e2e2e2"
yellow = "#b48800"

[schemes.material_iterm.primary]
background = "#101315"
foreground = "#8ea0b3"

[schemes.material_iterm.selection]
background = "#1a4d74"
text = "#f4f7fa"

[[schemes.nightfox.indexed_colors]]
color = "0xf4a261"
index = 16

[[schemes.nightfox.indexed_colors]]
color = "0xd67ad2"
index = 17

[schemes.nightfox.bright]
black = "0x475072"
blue = "0x84cee4"
cyan = "0x59f0ff"
green = "0x58cd8b"
magenta = "0xb8a1e3"
red = "0xd6616b"
white = "0xf2f2f2"
yellow = "0xffe37e"

[schemes.nightfox.normal]
black = "0x393b44"
blue = "0x719cd6"
cyan = "0x63cdcf"
green = "0x81b29a"
magenta = "0x9d79d6"
red = "0xc94f6d"
white = "0xdfdfe0"
yellow = "0xdbc074"

[schemes.nightfox.primary]
background = "0x192330"
foreground = "0xcdcecf"

[schemes.nord.bright]
black = "0x4c566a"
blue = "0xd8dee9"
cyan = "0x5e81ac"
green = "0x3b4252"
magenta = "0xeceff4"
red = "0xd08770"
white = "0x8fbcbb"
yellow = "0x434c5e"

[schemes.nord.cursor]
cursor = "0xe5e9f0"
text = "0x2e3440"

[schemes.nord.normal]
black = "0x2e3440"
blue = "0x81a1c1"
cyan = "0x88c0d0"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xe5e9f0"
yellow = "0xebcb8b"

[schemes.nord.primary]
background = "0x2e3440"
foreground = "0xe5e9f0"

[schemes.one-dark.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[schemes.one-dark.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[schemes.one-dark.primary]
background = "0x0b0c0e"
foreground = "0xc5cad3"

[scrolling]
history = 10000

[window]
decorations = "buttonless"

[window.dimensions]
columns = 150
lines = 60
