# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# Sppeed test: env STARSHIP_LOG=trace starship timings
scan_timeout = 10
command_timeout = 1200

# Custom formats:
# https://github.com/starship/starship/discussions/1252

# Starship module configs
# https://starship.rs/config

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
${custom.shiftcare_version}\
${custom.shiftcare_app_version}\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$docker_context\
$package\
$buf\
$c\
$cmake\
$cobol\
$container\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$fill\
$time\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# get icons from here: https://www.nerdfonts.com/cheat-sheet?v=1.0.20

[aws]
# format = "[$symbol $region]($style)|"
format = '[$symbol($profile )(\($region\) )]($style)'
style = "green"
symbol = " "
[aws.region_aliases]
ap-southeast-2 = "au"

[directory]
format = "[$path]($style) "
truncate_to_repo = false
truncation_length = 2
truncation_symbol = "…/"
style = "bg:blue fg:black" # can use hex too, example: bg:#DA627D

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_branch]
truncation_length = 32
truncation_symbol = "…"
style = "purple"

[git_status]
format = '([ \[$all_status$ahead_behind\]]($style)) '
style = "green"

[git_metrics]
disabled = false
format = '[+$added]($added_style)/[-$deleted]($deleted_style)|'
added_style = "green"
deleted_style = "red"

[nodejs]
format = "[$symbol ($version)]($style)|"
version_format = "${major}.${minor}"
style = "green"
symbol = ""

[package]
format = "[$symbol ($version)]($style)|"
display_private = true
version_format = "${raw}"
# style = "208"
style = "blue"
symbol = ""

[python]
format = "[$symbol ($version)]($style)|"
version_format = "${major}.${minor}"
symbol = ""
style = "green"

[ruby]
format = "[$symbol ($version)]($style)|"
version_format = "${major}.${minor}"
symbol = ""
style = "green"

[rust]
format = "[$symbol($version)]($style)|"
style = "red"
# symbol = " "

[custom.shiftcare_version]
description = "Shiftcare version"
command = "cat version 2>/dev/null"
# command = "cat version 2>/dev/null | tr -d '\n'"
# when = """ test "/Users/andras/work/sc/shiftcare" = $PWD """
detect_files = [ 'version' ]
symbol = "v"
style = "blue"
format = "[$symbol$output]($style) "


# [custom.shiftcare_app_version]
# description = "Shiftcare app version"
# command = """ grep "^project.ext.version*\\(Major\\|Minor\\|Patch\\)" android/app/build.gradle | awk -F "=" '{gsub (" ", "", $0);} NR > 1 {printf "." }; {printf "%s", $2}' """
# when = """ test "/Users/andras/work/sc/shiftcare-app" = $(pwd) """
# symbol = "v"
# style = "blue"
# format = "[$symbol$output]($style) "

[fill]
symbol = " "
style = ""

[cmd_duration]
min_time = 10
format = "[$duration]($style) "
show_milliseconds = true


